### ISSUE TITLE
Failed to run sample

### ISSUE THREAD

**Issue by esskar** [darryncampbell/DataWedge-Cordova-Sample#7]
Hey,

i tried to run your example, but it fails, here is the complete output

````
cordova platform add android
Using cordova-fetch for cordova-android@^8.0.0
Adding android project...
Creating Cordova project for the Android platform:
	Path: platforms/android
	Package: com.zebra.datawedgecordova
	Name: DataWedgeCordova
	Activity: MainActivity
	Android target: android-28
Subproject Path: CordovaLib
Subproject Path: app
Android project created with cordova-android@8.1.0
Plugin 'cordova-plugin-whitelist' found in config.xml... Migrating it to package.json
Plugin 'com-darryncampbell-cordova-plugin-intent' found in config.xml... Migrating it to package.json
Discovered saved plugin "cordova-plugin-whitelist". Adding it to the project
Installing "cordova-plugin-whitelist" for android
Adding cordova-plugin-whitelist to package.json
Discovered saved plugin "com-darryncampbell-cordova-plugin-intent". Adding it to the project
Installing "com-darryncampbell-cordova-plugin-intent" for android
Failed to install 'com-darryncampbell-cordova-plugin-intent': Error: Cannot find module 'cordova-common'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/esskar/Dev/Abat/DataWedgeCordova/platforms/android/cordova/lib/builders/builders.js:20:22)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
Failed to restore plugin "com-darryncampbell-cordova-plugin-intent" from config.xml. You might need to try adding it again. Error: Error: Cannot find module 'cordova-common'
```

**Comment by darryncampbell** [comment]
Can you please try removing and re-adding the plugin:
```
cordova plugin remove com-darryncampbell-cordova-plugin-intent
cordova plugin add com-darryncampbell-cordova-plugin-intent
```
I think Cordova changed something related to config.xml and this project needs to be updated.

**Comment by esskar** [comment]
Ok, it works like this. 

```
git clone https://github.com/darryncampbell/DataWedgeCordova.git
cd DataWedgeCordova
cordova plugin add com-darryncampbell-cordova-plugin-intent
cordova add android
```

**Comment by esskar** [comment]
ok, bu then there is a follow up problem

```
cordova run android --device

Unable to load PlatformApi from platform. Error: Cannot find module 'q'
Unhandled error. ('The platform "android" does not appear to be a valid cordova platform. It is missing API.js. android not supported.')
```

so it seems that is totally out-dated

**Comment by darryncampbell** [comment]
It was the same underlying issue, should be fixed in master with following commit: https://github.com/darryncampbell/DataWedgeCordova/commit/dd3efd26876193398e544afab6fff8eb3645689b

**Comment by esskar** [comment]
thanks. works. (y)
